CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    user_name TEXT NOT NULL,
    password TEXT NOT NULL,
    email TEXT NOT NULL,
    zip INTEGER,
    img_src TEXT,
    img_alt TEXT,
    hand TEXT NOT NULL,
    admin_status BOOLEAN NOT NULL
);