CREATE TABLE scorecards (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    disc_name TEXT NOT NULL,
    disc_type TEXT NOT NULL,
    stability TEXT NOT NULL,
    color TEXT NOT NULL,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    notes TEXT
);