CREATE TABLE discs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    disc_name TEXT NOT NULL,
    disc_type TEXT NOT NULL,
    disc_plastic TEXT NOT NULL,
    stability TEXT NOT NULL,
    color TEXT NOT NULL,
    speed INTEGER,
    glide INTEGER,
    turn INTEGER,
    fade INTEGER,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    notes TEXT
);