CREATE TABLE courses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    course_name TEXT NOT NULL,
    course_id INTEGER NOT NULL,
    holes INTEGER NOT NULL,
    course_address TEXT NOT NULL,
    course_description TEXT,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    notes TEXT
);