CREATE TABLE courses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    designer TEXT,
    terrain TEXT,
    tees TEXT, 
    baskets TEXT,
    holes INTEGER NOT NULL,
    address TEXT NOT NULL,
    zip INTEGER,
    description TEXT,
    map_url TEXT,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    notes TEXT
);