CREATE TABLE holes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    layout_id INTEGER REFERENCES layouts(id) ON DELETE CASCADE NOT NULL,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    position INTEGER,
    position_notes TEXT,
    distance INTEGER,
    notes TEXT,
    par INTEGER,
    score INTEGER
);