CREATE TABLE strokes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    scorecard_id INTEGER REFERENCES scorecards(id) ON DELETE CASCADE NOT NULL,
    position_id INTEGER REFERENCES positions(id) ON DELETE CASCADE NOT NULL,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    disc_id INTEGER REFERENCES discs(id),
    hand TEXT NOT NULL,
    shot_type TEXT NOT NULL,
    shot_result TEXT NOT NULL,
    wind TEXT,
    wind_direction TEXT,
    notes TEXT
);