CREATE TABLE positions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    course_id INTEGER REFERENCES courses(id) NOT NULL,
    hole_id INTEGER REFERENCES holes(id) NOT NULL,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    position TEXT NOT NULL,
    position_notes TEXT,
    distance INTEGER,
    notes TEXT,
    par INTEGER
);